services:
  db:
    image: postgres:15
    container_name: sandwichscan-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sandwichscan_default

  web:
    build: .
    container_name: sandwichscan-web
    command: >
      bash -c "uv venv &&
      uv pip install . &&
      uv pip install --group dev &&
      source .venv/bin/activate &&
      uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - "8000:8000" # for fastapi
      - "8888:8888" # for jupyter notebook when debugging
    depends_on:
      - db
    networks:
      - sandwichscan_default

volumes:
  postgres_data:

networks:
  sandwichscan_default:
    external: true
