"""default 0

Revision ID: 046b4afcd660
Revises: ad58f5583817
Create Date: 2025-09-16 17:22:37.885151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "046b4afcd660"
down_revision: Union[str, None] = "ad58f5583817"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sandwich_attacks",
        "revenue_base_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "gas_fee_wei_attacker",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "profit_base_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "harm_base_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sandwich_attacks",
        "harm_base_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=True,
    )
    op.alter_column(
        "sandwich_attacks",
        "profit_base_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=True,
    )
    op.alter_column(
        "sandwich_attacks",
        "gas_fee_wei_attacker",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=True,
    )
    op.alter_column(
        "sandwich_attacks",
        "revenue_base_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=True,
    )
    # ### end Alembic commands ###
