"""change defi pool relation

Revision ID: 0a57c111e505
Revises: bd265b70e4c6
Create Date: 2025-09-16 09:57:14.536126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a57c111e505"
down_revision: Union[str, None] = "bd265b70e4c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wrapped_native_tokens",
        sa.Column("usd_uniswap_v2_pool_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "wrapped_native_tokens",
        sa.Column("usd_uniswap_v3_pool_id", sa.Integer(), nullable=True),
    )
    op.drop_index(
        "idx_wrapped_native_tokens_chain_pool", table_name="wrapped_native_tokens"
    )
    op.drop_index(
        "ix_wrapped_native_tokens_usd_pool_id", table_name="wrapped_native_tokens"
    )
    op.create_index(
        "idx_wrapped_native_tokens_chain_v2_pool",
        "wrapped_native_tokens",
        ["chain_id", "usd_uniswap_v2_pool_id"],
        unique=False,
    )
    op.create_index(
        "idx_wrapped_native_tokens_chain_v3_pool",
        "wrapped_native_tokens",
        ["chain_id", "usd_uniswap_v3_pool_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wrapped_native_tokens_usd_uniswap_v2_pool_id"),
        "wrapped_native_tokens",
        ["usd_uniswap_v2_pool_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wrapped_native_tokens_usd_uniswap_v3_pool_id"),
        "wrapped_native_tokens",
        ["usd_uniswap_v3_pool_id"],
        unique=False,
    )
    op.drop_constraint(
        "wrapped_native_tokens_usd_pool_id_fkey",
        "wrapped_native_tokens",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "wrapped_native_tokens",
        "defi_pools",
        ["usd_uniswap_v3_pool_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "wrapped_native_tokens",
        "defi_pools",
        ["usd_uniswap_v2_pool_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("wrapped_native_tokens", "usd_pool_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wrapped_native_tokens",
        sa.Column("usd_pool_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "wrapped_native_tokens", type_="foreignkey")
    op.drop_constraint(None, "wrapped_native_tokens", type_="foreignkey")
    op.create_foreign_key(
        "wrapped_native_tokens_usd_pool_id_fkey",
        "wrapped_native_tokens",
        "defi_pools",
        ["usd_pool_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(
        op.f("ix_wrapped_native_tokens_usd_uniswap_v3_pool_id"),
        table_name="wrapped_native_tokens",
    )
    op.drop_index(
        op.f("ix_wrapped_native_tokens_usd_uniswap_v2_pool_id"),
        table_name="wrapped_native_tokens",
    )
    op.drop_index(
        "idx_wrapped_native_tokens_chain_v3_pool", table_name="wrapped_native_tokens"
    )
    op.drop_index(
        "idx_wrapped_native_tokens_chain_v2_pool", table_name="wrapped_native_tokens"
    )
    op.create_index(
        "ix_wrapped_native_tokens_usd_pool_id",
        "wrapped_native_tokens",
        ["usd_pool_id"],
        unique=False,
    )
    op.create_index(
        "idx_wrapped_native_tokens_chain_pool",
        "wrapped_native_tokens",
        ["chain_id", "usd_pool_id"],
        unique=False,
    )
    op.drop_column("wrapped_native_tokens", "usd_uniswap_v3_pool_id")
    op.drop_column("wrapped_native_tokens", "usd_uniswap_v2_pool_id")
    # ### end Alembic commands ###
