"""add gas price

Revision ID: 1b256142ce86
Revises: 2a57caf5b5fc
Create Date: 2025-09-16 06:18:50.276764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b256142ce86"
down_revision: Union[str, None] = "2a57caf5b5fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sandwich_attacks", sa.Column("base_token_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column("profit_base", sa.Numeric(precision=38, scale=18), nullable=True),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column("harm_base", sa.Numeric(precision=38, scale=18), nullable=True),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "gas_fee_eth_attacker", sa.Numeric(precision=38, scale=18), nullable=True
        ),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "gas_fee_usd_attacker", sa.Numeric(precision=38, scale=18), nullable=True
        ),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "gas_fee_eth_total", sa.Numeric(precision=38, scale=18), nullable=True
        ),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "gas_fee_usd_total", sa.Numeric(precision=38, scale=18), nullable=True
        ),
    )
    op.alter_column(
        "sandwich_attacks", "victim_address", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "sandwich_attacks",
        "victim_base_size_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=True,
    )
    op.alter_column(
        "sandwich_attacks",
        "profit_base_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=True,
    )
    op.alter_column(
        "sandwich_attacks",
        "harm_base_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=True,
    )
    op.alter_column(
        "sandwich_attacks",
        "gas_fee_wei_attacker",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=True,
    )
    op.alter_column(
        "sandwich_attacks",
        "revenue_usd",
        existing_type=sa.NUMERIC(precision=38, scale=18),
        nullable=True,
    )
    op.alter_column(
        "sandwich_attacks",
        "cost_usd",
        existing_type=sa.NUMERIC(precision=38, scale=18),
        nullable=True,
    )
    op.alter_column(
        "sandwich_attacks",
        "profit_usd",
        existing_type=sa.NUMERIC(precision=38, scale=18),
        nullable=True,
    )
    op.alter_column(
        "sandwich_attacks",
        "harm_usd",
        existing_type=sa.NUMERIC(precision=38, scale=18),
        nullable=True,
    )
    op.drop_index(
        "ix_sandwich_attacks_base_priced_pool_id", table_name="sandwich_attacks"
    )
    op.create_index(
        op.f("ix_sandwich_attacks_base_token_id"),
        "sandwich_attacks",
        ["base_token_id"],
        unique=False,
    )
    op.drop_constraint(
        "sandwich_attacks_base_priced_pool_id_fkey",
        "sandwich_attacks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sandwich_attacks",
        "tokens",
        ["base_token_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("sandwich_attacks", "priced_block_number")
    op.drop_column("sandwich_attacks", "base_priced_pool_id")
    op.drop_column("sandwich_attacks", "is_base_stable_coin")
    op.add_column(
        "transactions",
        sa.Column("gas_price_usd", sa.Numeric(precision=38, scale=18), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "gas_price_usd")
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "is_base_stable_coin", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "base_priced_pool_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "priced_block_number", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "sandwich_attacks", type_="foreignkey")
    op.create_foreign_key(
        "sandwich_attacks_base_priced_pool_id_fkey",
        "sandwich_attacks",
        "defi_pools",
        ["base_priced_pool_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_sandwich_attacks_base_token_id"), table_name="sandwich_attacks"
    )
    op.create_index(
        "ix_sandwich_attacks_base_priced_pool_id",
        "sandwich_attacks",
        ["base_priced_pool_id"],
        unique=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "harm_usd",
        existing_type=sa.NUMERIC(precision=38, scale=18),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "profit_usd",
        existing_type=sa.NUMERIC(precision=38, scale=18),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "cost_usd",
        existing_type=sa.NUMERIC(precision=38, scale=18),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "revenue_usd",
        existing_type=sa.NUMERIC(precision=38, scale=18),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "gas_fee_wei_attacker",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "harm_base_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "profit_base_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks",
        "victim_base_size_raw",
        existing_type=sa.NUMERIC(precision=78, scale=0),
        nullable=False,
    )
    op.alter_column(
        "sandwich_attacks", "victim_address", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("sandwich_attacks", "gas_fee_usd_total")
    op.drop_column("sandwich_attacks", "gas_fee_eth_total")
    op.drop_column("sandwich_attacks", "gas_fee_usd_attacker")
    op.drop_column("sandwich_attacks", "gas_fee_eth_attacker")
    op.drop_column("sandwich_attacks", "harm_base")
    op.drop_column("sandwich_attacks", "profit_base")
    op.drop_column("sandwich_attacks", "base_token_id")
    # ### end Alembic commands ###
