"""add sandwich attack

Revision ID: 251c44756b78
Revises: 2e1eebe380ec
Create Date: 2025-09-21 05:56:50.375930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "251c44756b78"
down_revision: Union[str, None] = "2e1eebe380ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "gas_fee_base_raw",
            sa.Numeric(precision=78, scale=0),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sandwich_attacks", "gas_fee_base_raw")
    # ### end Alembic commands ###
