"""change sandwich attack

Revision ID: 2a57caf5b5fc
Revises: f124155dd772
Create Date: 2025-09-15 14:28:23.078687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a57caf5b5fc'
down_revision: Union[str, None] = 'f124155dd772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandwich_attacks', sa.Column('base_priced_pool_id', sa.Integer(), nullable=True))
    op.add_column('sandwich_attacks', sa.Column('is_base_stable_coin', sa.Boolean(), nullable=False))
    op.add_column('sandwich_attacks', sa.Column('priced_block_number', sa.Integer(), nullable=False))
    op.alter_column('sandwich_attacks', 'victim_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sandwich_attacks', 'victim_base_size_raw',
               existing_type=sa.NUMERIC(precision=78, scale=0),
               nullable=False)
    op.alter_column('sandwich_attacks', 'profit_base_raw',
               existing_type=sa.NUMERIC(precision=78, scale=0),
               nullable=False)
    op.alter_column('sandwich_attacks', 'harm_base_raw',
               existing_type=sa.NUMERIC(precision=78, scale=0),
               nullable=False)
    op.alter_column('sandwich_attacks', 'gas_fee_wei_attacker',
               existing_type=sa.NUMERIC(precision=78, scale=0),
               nullable=False)
    op.alter_column('sandwich_attacks', 'revenue_usd',
               existing_type=sa.NUMERIC(precision=38, scale=18),
               nullable=False)
    op.alter_column('sandwich_attacks', 'cost_usd',
               existing_type=sa.NUMERIC(precision=38, scale=18),
               nullable=False)
    op.alter_column('sandwich_attacks', 'profit_usd',
               existing_type=sa.NUMERIC(precision=38, scale=18),
               nullable=False)
    op.alter_column('sandwich_attacks', 'harm_usd',
               existing_type=sa.NUMERIC(precision=38, scale=18),
               nullable=False)
    op.drop_index('ix_sandwich_attacks_base_token_id', table_name='sandwich_attacks')
    op.create_index(op.f('ix_sandwich_attacks_base_priced_pool_id'), 'sandwich_attacks', ['base_priced_pool_id'], unique=False)
    op.drop_constraint('sandwich_attacks_base_token_id_fkey', 'sandwich_attacks', type_='foreignkey')
    op.create_foreign_key(None, 'sandwich_attacks', 'defi_pools', ['base_priced_pool_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sandwich_attacks', 'gas_fee_usd_total')
    op.drop_column('sandwich_attacks', 'profit_base')
    op.drop_column('sandwich_attacks', 'detected_by')
    op.drop_column('sandwich_attacks', 'gas_fee_eth_attacker')
    op.drop_column('sandwich_attacks', 'base_token_id')
    op.drop_column('sandwich_attacks', 'notes')
    op.drop_column('sandwich_attacks', 'gas_fee_eth_total')
    op.drop_column('sandwich_attacks', 'gas_fee_usd_attacker')
    op.drop_column('sandwich_attacks', 'harm_base')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandwich_attacks', sa.Column('harm_base', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True))
    op.add_column('sandwich_attacks', sa.Column('gas_fee_usd_attacker', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True))
    op.add_column('sandwich_attacks', sa.Column('gas_fee_eth_total', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True))
    op.add_column('sandwich_attacks', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sandwich_attacks', sa.Column('base_token_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sandwich_attacks', sa.Column('gas_fee_eth_attacker', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True))
    op.add_column('sandwich_attacks', sa.Column('detected_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sandwich_attacks', sa.Column('profit_base', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True))
    op.add_column('sandwich_attacks', sa.Column('gas_fee_usd_total', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sandwich_attacks', type_='foreignkey')
    op.create_foreign_key('sandwich_attacks_base_token_id_fkey', 'sandwich_attacks', 'tokens', ['base_token_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_sandwich_attacks_base_priced_pool_id'), table_name='sandwich_attacks')
    op.create_index('ix_sandwich_attacks_base_token_id', 'sandwich_attacks', ['base_token_id'], unique=False)
    op.alter_column('sandwich_attacks', 'harm_usd',
               existing_type=sa.NUMERIC(precision=38, scale=18),
               nullable=True)
    op.alter_column('sandwich_attacks', 'profit_usd',
               existing_type=sa.NUMERIC(precision=38, scale=18),
               nullable=True)
    op.alter_column('sandwich_attacks', 'cost_usd',
               existing_type=sa.NUMERIC(precision=38, scale=18),
               nullable=True)
    op.alter_column('sandwich_attacks', 'revenue_usd',
               existing_type=sa.NUMERIC(precision=38, scale=18),
               nullable=True)
    op.alter_column('sandwich_attacks', 'gas_fee_wei_attacker',
               existing_type=sa.NUMERIC(precision=78, scale=0),
               nullable=True)
    op.alter_column('sandwich_attacks', 'harm_base_raw',
               existing_type=sa.NUMERIC(precision=78, scale=0),
               nullable=True)
    op.alter_column('sandwich_attacks', 'profit_base_raw',
               existing_type=sa.NUMERIC(precision=78, scale=0),
               nullable=True)
    op.alter_column('sandwich_attacks', 'victim_base_size_raw',
               existing_type=sa.NUMERIC(precision=78, scale=0),
               nullable=True)
    op.alter_column('sandwich_attacks', 'victim_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sandwich_attacks', 'priced_block_number')
    op.drop_column('sandwich_attacks', 'is_base_stable_coin')
    op.drop_column('sandwich_attacks', 'base_priced_pool_id')
    # ### end Alembic commands ###
