"""add defi_pool id

Revision ID: 2e1eebe380ec
Revises: 412780caef6d
Create Date: 2025-09-20 08:47:38.020152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e1eebe380ec"
down_revision: Union[str, None] = "412780caef6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sandwich_attacks", "defi_pool_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sandwich_attacks", "defi_pool_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
