"""add logo url

Revision ID: 333d010e152a
Revises: 828cb3d40007
Create Date: 2025-09-19 10:16:56.567851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "333d010e152a"
down_revision: Union[str, None] = "828cb3d40007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tokens", sa.Column("logo_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens", "logo_url")
    # ### end Alembic commands ###
