"""add block timestamp

Revision ID: 3bebe9c6b6bc
Revises: 8c57e8cb3153
Create Date: 2025-09-21 06:41:18.280898

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3bebe9c6b6bc"
down_revision: Union[str, None] = "8c57e8cb3153"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "block_timestamp",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sandwich_attacks", "block_timestamp")
    # ### end Alembic commands ###
