"""add defi_pool id

Revision ID: 412780caef6d
Revises: 333d010e152a
Create Date: 2025-09-20 08:43:51.670863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "412780caef6d"
down_revision: Union[str, None] = "333d010e152a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sandwich_attacks", sa.Column("defi_pool_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_sandwich_attacks_defi_pool_id"),
        "sandwich_attacks",
        ["defi_pool_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "sandwich_attacks",
        "defi_pools",
        ["defi_pool_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sandwich_attacks", type_="foreignkey")
    op.drop_index(
        op.f("ix_sandwich_attacks_defi_pool_id"), table_name="sandwich_attacks"
    )
    op.drop_column("sandwich_attacks", "defi_pool_id")
    # ### end Alembic commands ###
