"""add columns

Revision ID: 601e012822c4
Revises: 14ad387cfb4d
Create Date: 2025-09-13 13:01:03.153904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "601e012822c4"
down_revision: Union[str, None] = "14ad387cfb4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add as nullable with server_default
    op.add_column(
        "defi_pools",
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "defi_pools", sa.Column("last_swap_block", sa.BigInteger(), nullable=True)
    )
    op.add_column("defi_pools", sa.Column("last_swap_at", sa.DateTime(), nullable=True))
    op.add_column(
        "defi_pools",
        sa.Column("swaps_24h", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "defi_pools",
        sa.Column("swaps_7d", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "defi_pools",
        sa.Column("activity_score", sa.Integer(), nullable=False, server_default="0"),
    )
    # Step 2: Remove server_default for is_active and set nullable to False
    op.alter_column("defi_pools", "is_active", server_default=None, nullable=False)
    op.alter_column("defi_pools", "swaps_24h", server_default=None, nullable=False)
    op.alter_column("defi_pools", "swaps_7d", server_default=None, nullable=False)
    op.alter_column("defi_pools", "activity_score", server_default=None, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("defi_pools", "activity_score")
    op.drop_column("defi_pools", "swaps_7d")
    op.drop_column("defi_pools", "swaps_24h")
    op.drop_column("defi_pools", "last_swap_at")
    op.drop_column("defi_pools", "last_swap_block")
    op.drop_column("defi_pools", "is_active")
    # ### end Alembic commands ###
