"""remove stable coin on chain

Revision ID: 7e9fb5f16f8a
Revises: 8ad3d2bd5a5e
Create Date: 2025-09-14 13:43:21.198538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e9fb5f16f8a"
down_revision: Union[str, None] = "8ad3d2bd5a5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chains", "usd_stable_coin_address")
    op.drop_column("swaps", "base_is_token0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "swaps",
        sa.Column("base_is_token0", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "chains",
        sa.Column(
            "usd_stable_coin_address", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
