"""add exploper url

Revision ID: 828cb3d40007
Revises: 9e58687c2b57
Create Date: 2025-09-19 09:56:59.250305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "828cb3d40007"
down_revision: Union[str, None] = "9e58687c2b57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chains",
        sa.Column("explorer_url", sa.String(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chains", "explorer_url")
    # ### end Alembic commands ###
