"""add cost profit revenue

Revision ID: 8ad3d2bd5a5e
Revises: 601e012822c4
Create Date: 2025-09-14 10:48:54.483411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ad3d2bd5a5e"
down_revision: Union[str, None] = "601e012822c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sandwich_attacks",
        sa.Column("revenue_usd", sa.Numeric(precision=38, scale=18), nullable=True),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column("cost_usd", sa.Numeric(precision=38, scale=18), nullable=True),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column("profit_usd", sa.Numeric(precision=38, scale=18), nullable=True),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column("harm_usd", sa.Numeric(precision=38, scale=18), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sandwich_attacks", "harm_usd")
    op.drop_column("sandwich_attacks", "profit_usd")
    op.drop_column("sandwich_attacks", "cost_usd")
    op.drop_column("sandwich_attacks", "revenue_usd")
    # ### end Alembic commands ###
