"""victim null false

Revision ID: 8c57e8cb3153
Revises: 251c44756b78
Create Date: 2025-09-21 06:17:06.474368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c57e8cb3153"
down_revision: Union[str, None] = "251c44756b78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sandwich_attacks", "victim_address", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sandwich_attacks", "victim_address", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
