"""nullable false  defi_version

Revision ID: 9e58687c2b57
Revises: c041573d352e
Create Date: 2025-09-19 09:30:29.544759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e58687c2b57"
down_revision: Union[str, None] = "c041573d352e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sandwich_attacks",
        "defi_version_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sandwich_attacks", "defi_version_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
