"""add last block

Revision ID: a2e7a159e297
Revises: 686cbc2b9ddd
Create Date: 2025-09-11 16:42:03.931455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e7a159e297'
down_revision: Union[str, None] = '686cbc2b9ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defi_factories', sa.Column('last_gotten_block_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defi_factories', 'last_gotten_block_number')
    # ### end Alembic commands ###
