"""create usd stable coin

Revision ID: a89fc910254d
Revises: 7e9fb5f16f8a
Create Date: 2025-09-14 14:13:53.050280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a89fc910254d"
down_revision: Union[str, None] = "7e9fb5f16f8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usd_stable_coins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["chain_id"], ["chains.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chain_id", "token_id", name="uq_usd_stable_coins_chain_token"
        ),
    )
    op.create_index(
        "idx_usd_stable_coins_chain_priority",
        "usd_stable_coins",
        ["chain_id", "priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usd_stable_coins_chain_id"),
        "usd_stable_coins",
        ["chain_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usd_stable_coins_token_id"),
        "usd_stable_coins",
        ["token_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usd_stable_coins_token_id"), table_name="usd_stable_coins")
    op.drop_index(op.f("ix_usd_stable_coins_chain_id"), table_name="usd_stable_coins")
    op.drop_index("idx_usd_stable_coins_chain_priority", table_name="usd_stable_coins")
    op.drop_table("usd_stable_coins")
    # ### end Alembic commands ###
