"""fix sandwich attack

Revision ID: ab6eb5cba74a
Revises: 0a57c111e505
Create Date: 2025-09-16 12:14:33.995171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab6eb5cba74a"
down_revision: Union[str, None] = "0a57c111e505"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sandwich_attacks", "gas_fee_eth_attacker")
    op.drop_column("sandwich_attacks", "gas_fee_eth_total")
    op.drop_column("sandwich_attacks", "gas_fee_usd_attacker")
    op.drop_column("sandwich_attacks", "harm_base")
    op.drop_column("sandwich_attacks", "profit_base")
    op.drop_column("sandwich_attacks", "gas_fee_usd_total")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "gas_fee_usd_total",
            sa.NUMERIC(precision=38, scale=18),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "profit_base",
            sa.NUMERIC(precision=38, scale=18),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "harm_base",
            sa.NUMERIC(precision=38, scale=18),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "gas_fee_usd_attacker",
            sa.NUMERIC(precision=38, scale=18),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "gas_fee_eth_total",
            sa.NUMERIC(precision=38, scale=18),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "sandwich_attacks",
        sa.Column(
            "gas_fee_eth_attacker",
            sa.NUMERIC(precision=38, scale=18),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
