"""fix sandwich attack

Revision ID: ad58f5583817
Revises: e1338063a28a
Create Date: 2025-09-16 17:19:43.214939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad58f5583817'
down_revision: Union[str, None] = 'e1338063a28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandwich_attacks', sa.Column('revenue_base_raw', sa.Numeric(precision=78, scale=0), nullable=True))
    op.drop_column('sandwich_attacks', 'victim_base_size_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandwich_attacks', sa.Column('victim_base_size_raw', sa.NUMERIC(precision=78, scale=0), autoincrement=False, nullable=True))
    op.drop_column('sandwich_attacks', 'revenue_base_raw')
    # ### end Alembic commands ###
