"""add WrappedNativeToken

Revision ID: bd265b70e4c6
Revises: 1b256142ce86
Create Date: 2025-09-16 09:39:27.927304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd265b70e4c6"
down_revision: Union[str, None] = "1b256142ce86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wrapped_native_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("usd_stable_coin_id", sa.Integer(), nullable=True),
        sa.Column("usd_pool_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["chain_id"], ["chains.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["usd_pool_id"], ["defi_pools.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["usd_stable_coin_id"], ["usd_stable_coins.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chain_id", name="uq_wrapped_native_tokens_chain"),
    )
    op.create_index(
        "idx_wrapped_native_tokens_chain_pool",
        "wrapped_native_tokens",
        ["chain_id", "usd_pool_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wrapped_native_tokens_chain_id"),
        "wrapped_native_tokens",
        ["chain_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wrapped_native_tokens_token_id"),
        "wrapped_native_tokens",
        ["token_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wrapped_native_tokens_usd_pool_id"),
        "wrapped_native_tokens",
        ["usd_pool_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wrapped_native_tokens_usd_stable_coin_id"),
        "wrapped_native_tokens",
        ["usd_stable_coin_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wrapped_native_tokens_usd_stable_coin_id"),
        table_name="wrapped_native_tokens",
    )
    op.drop_index(
        op.f("ix_wrapped_native_tokens_usd_pool_id"), table_name="wrapped_native_tokens"
    )
    op.drop_index(
        op.f("ix_wrapped_native_tokens_token_id"), table_name="wrapped_native_tokens"
    )
    op.drop_index(
        op.f("ix_wrapped_native_tokens_chain_id"), table_name="wrapped_native_tokens"
    )
    op.drop_index(
        "idx_wrapped_native_tokens_chain_pool", table_name="wrapped_native_tokens"
    )
    op.drop_table("wrapped_native_tokens")
    # ### end Alembic commands ###
