"""add defi_version_id on sandwich attack

Revision ID: c041573d352e
Revises: 7b2a9d5f1c3a
Create Date: 2025-09-19 09:11:20.183283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c041573d352e'
down_revision: Union[str, None] = '7b2a9d5f1c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandwich_attacks', sa.Column('defi_version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sandwich_attacks_defi_version_id'), 'sandwich_attacks', ['defi_version_id'], unique=False)
    op.create_foreign_key(None, 'sandwich_attacks', 'defi_versions', ['defi_version_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_swaps_tx_pool_log', table_name='swaps')
    op.drop_index('idx_transactions_from_lower', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_transactions_from_lower', 'transactions', ['chain_id', sa.literal_column('lower(from_address::text)')], unique=False)
    op.create_index('idx_swaps_tx_pool_log', 'swaps', ['transaction_id', 'defi_pool_id', 'log_index'], unique=False)
    op.drop_constraint(None, 'sandwich_attacks', type_='foreignkey')
    op.drop_index(op.f('ix_sandwich_attacks_defi_version_id'), table_name='sandwich_attacks')
    op.drop_column('sandwich_attacks', 'defi_version_id')
    # ### end Alembic commands ###
