"""change swap

Revision ID: d0b163a68e65
Revises: a89fc910254d
Create Date: 2025-09-14 14:32:43.289882

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0b163a68e65"
down_revision: Union[str, None] = "a89fc910254d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_swaps_chain_block", table_name="swaps")
    op.drop_index("idx_swaps_pool_block", table_name="swaps")
    op.drop_constraint("uq_swaps_txhash_logindex", "swaps", type_="unique")
    op.create_unique_constraint(
        "uq_swaps_tx_log_index", "swaps", ["transaction_id", "log_index"]
    )
    op.drop_column("swaps", "block_number")
    op.drop_column("swaps", "tx_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "swaps", sa.Column("tx_hash", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "swaps",
        sa.Column("block_number", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("uq_swaps_tx_log_index", "swaps", type_="unique")
    op.create_unique_constraint(
        "uq_swaps_txhash_logindex", "swaps", ["tx_hash", "log_index"]
    )
    op.create_index(
        "idx_swaps_pool_block", "swaps", ["defi_pool_id", "block_number"], unique=False
    )
    op.create_index(
        "idx_swaps_chain_block", "swaps", ["chain_id", "block_number"], unique=False
    )
    # ### end Alembic commands ###
