"""add index

Revision ID: e1338063a28a
Revises: ab6eb5cba74a
Create Date: 2025-09-16 13:56:37.967202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1338063a28a'
down_revision: Union[str, None] = 'ab6eb5cba74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_swaps_pool_sell_buy', 'swaps', ['defi_pool_id', 'sell_token_id', 'buy_token_id'], unique=False)
    op.create_index('idx_swaps_pool_tx_log', 'swaps', ['defi_pool_id', 'transaction_id', 'log_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_swaps_pool_tx_log', table_name='swaps')
    op.drop_index('idx_swaps_pool_sell_buy', table_name='swaps')
    # ### end Alembic commands ###
