"""add token id

Revision ID: f124155dd772
Revises: d0b163a68e65
Create Date: 2025-09-14 15:20:56.284290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f124155dd772"
down_revision: Union[str, None] = "d0b163a68e65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("swaps", sa.Column("sell_token_id", sa.Integer(), nullable=True))
    op.add_column("swaps", sa.Column("buy_token_id", sa.Integer(), nullable=True))
    op.drop_index("idx_swaps_base_direction", table_name="swaps")
    op.drop_index("ix_swaps_base_token_id", table_name="swaps")
    op.create_index(
        op.f("ix_swaps_buy_token_id"), "swaps", ["buy_token_id"], unique=False
    )
    op.create_index(
        op.f("ix_swaps_sell_token_id"), "swaps", ["sell_token_id"], unique=False
    )
    op.drop_constraint("swaps_base_token_id_fkey", "swaps", type_="foreignkey")
    op.create_foreign_key(
        None, "swaps", "tokens", ["buy_token_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "swaps", "tokens", ["sell_token_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("swaps", "direction")
    op.drop_column("swaps", "base_token_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "swaps",
        sa.Column("base_token_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "swaps",
        sa.Column("direction", sa.SMALLINT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "swaps", type_="foreignkey")
    op.drop_constraint(None, "swaps", type_="foreignkey")
    op.create_foreign_key(
        "swaps_base_token_id_fkey",
        "swaps",
        "tokens",
        ["base_token_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_swaps_sell_token_id"), table_name="swaps")
    op.drop_index(op.f("ix_swaps_buy_token_id"), table_name="swaps")
    op.create_index("ix_swaps_base_token_id", "swaps", ["base_token_id"], unique=False)
    op.create_index(
        "idx_swaps_base_direction",
        "swaps",
        ["base_token_id", "direction"],
        unique=False,
    )
    op.drop_column("swaps", "buy_token_id")
    op.drop_column("swaps", "sell_token_id")
    # ### end Alembic commands ###
